databases:
  - name: postgres
    ipAllowList: []


services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: NhkWrfU1jaTopGEk00T1BM8RhksnovCnS8RuNyt0vWo6XDXGhNLe86GD0fN0Ew6nIkDGqxzCh8DWadBnY8e5L6vUlRVg53cwvkS8SIfe7mr+CyxYgmq/vXu7KU9EKG0uylV1twtsYu4X3c1dOuny/L1dPcncYyT7s/x4UzHxHcz8VAGOq4NcfYdoWZm5imvRhsQCAApjzxJjXyUa3gBjYXhdOS16kFvPIlitCIH2XH2YJkJklSfYxQ/f9OrWf11qgd1n9nhVGudx2JQgpJHW7/inGm/7Lhwyj1sF6U0+TpQ2W7UGVDDQ/QCEB2gEj7HPj6pSfwA21eglOT6lZuYP7aRRZEy++kJfnfjD7Gg/M8d5ylESFKbzb9B5HA0PNWlGYVrG6QhzXixDA/rAXa4y009nny1rGqvi9xGo--fjrTYm3GNRS+QRBU--+35cDA3bOtZKSgurTvw1XA==
        sync: false
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noviction
