databases:
  - name: postgres
    ipAllowList: []
    databaseName: House-Cleaning-App-backend
    user: House-Cleaning-App-backend

services:
  - type: web
    name: House-Cleaning-App-backend
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false